+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Wed Apr 26 14:30:49 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL openvswitch
+ pkgs=openvswitch
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs openvswitch --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpe4utpgo8
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpe4utpgo8
+ service=ovsdb-server.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-04-26 14:32:33'
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Wed Apr 26 14:32:34 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Wed Apr 26 14:32:34 2023 - INFO  - Start testing...
+ service ovsdb-server.service restart
oe_test_service_ovsdb-server.sh: line 32: service: command not found
+ CHECK_RESULT 127 0 0 'ovsdb-server.service restart failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='ovsdb-server.service restart failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'ovsdb-server.service restart failed'
+ LOG_ERROR 'ovsdb-server.service restart failed'
+ message='ovsdb-server.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ovsdb-server.service restart failed'
Wed Apr 26 14:32:35 2023 - ERROR - ovsdb-server.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ovsdb-server.sh line 33'
+ message='oe_test_service_ovsdb-server.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ovsdb-server.sh line 33'
Wed Apr 26 14:32:36 2023 - ERROR - oe_test_service_ovsdb-server.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ service ovsdb-server.service stop
oe_test_service_ovsdb-server.sh: line 34: service: command not found
+ CHECK_RESULT 127 0 0 'ovsdb-server.service stop failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='ovsdb-server.service stop failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'ovsdb-server.service stop failed'
+ LOG_ERROR 'ovsdb-server.service stop failed'
+ message='ovsdb-server.service stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ovsdb-server.service stop failed'
Wed Apr 26 14:32:37 2023 - ERROR - ovsdb-server.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ovsdb-server.sh line 35'
+ message='oe_test_service_ovsdb-server.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ovsdb-server.sh line 35'
Wed Apr 26 14:32:37 2023 - ERROR - oe_test_service_ovsdb-server.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ service ovsdb-server.service start
oe_test_service_ovsdb-server.sh: line 36: service: command not found
+ CHECK_RESULT 127 0 0 'ovsdb-server.service start failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='ovsdb-server.service start failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'ovsdb-server.service start failed'
+ LOG_ERROR 'ovsdb-server.service start failed'
+ message='ovsdb-server.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ovsdb-server.service start failed'
Wed Apr 26 14:32:38 2023 - ERROR - ovsdb-server.service start failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ovsdb-server.sh line 37'
+ message='oe_test_service_ovsdb-server.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ovsdb-server.sh line 37'
Wed Apr 26 14:32:39 2023 - ERROR - oe_test_service_ovsdb-server.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ service ovsdb-server.service status
oe_test_service_ovsdb-server.sh: line 38: service: command not found
+ grep 'Active: active (running)'
+ CHECK_RESULT 1 0 0 'ovsdb-server.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ovsdb-server.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ovsdb-server.service start failed'
+ LOG_ERROR 'ovsdb-server.service start failed'
+ message='ovsdb-server.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ovsdb-server.service start failed'
Wed Apr 26 14:32:40 2023 - ERROR - ovsdb-server.service start failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ovsdb-server.sh line 39'
+ message='oe_test_service_ovsdb-server.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ovsdb-server.sh line 39'
Wed Apr 26 14:32:41 2023 - ERROR - oe_test_service_ovsdb-server.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ journalctl --since '2023-04-26 14:32:33' -u ovsdb-server.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ CHECK_RESULT 1 1 0 'There is an error message for the log of ovsdb-server.service'
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log='There is an error message for the log of ovsdb-server.service'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ service ovsdb-server.service start
oe_test_service_ovsdb-server.sh: line 42: service: command not found
+ sed -i 's\ExecStart=/usr/share/openvswitch/scripts/ovs-ctl\ExecStart=/usr/share/openvswitch/scripts/ovs-ctl --no-mlockall\g' /usr/lib/systemd/system/ovsdb-server.service
+ systemctl daemon-reload
+ service ovsdb-server.service reload
oe_test_service_ovsdb-server.sh: line 45: service: command not found
+ CHECK_RESULT 127 0 0 'ovsdb-server.service reload failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='ovsdb-server.service reload failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'ovsdb-server.service reload failed'
+ LOG_ERROR 'ovsdb-server.service reload failed'
+ message='ovsdb-server.service reload failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ovsdb-server.service reload failed'
Wed Apr 26 14:32:47 2023 - ERROR - ovsdb-server.service reload failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ovsdb-server.sh line 46'
+ message='oe_test_service_ovsdb-server.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ovsdb-server.sh line 46'
Wed Apr 26 14:32:48 2023 - ERROR - oe_test_service_ovsdb-server.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ service ovsdb-server.service status
+ grep 'Active: active'
oe_test_service_ovsdb-server.sh: line 47: service: command not found
+ CHECK_RESULT 1 0 0 'ovsdb-server.service reload causes the service status to change'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ovsdb-server.service reload causes the service status to change'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ovsdb-server.service reload causes the service status to change'
+ LOG_ERROR 'ovsdb-server.service reload causes the service status to change'
+ message='ovsdb-server.service reload causes the service status to change'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ovsdb-server.service reload causes the service status to change'
Wed Apr 26 14:32:49 2023 - ERROR - ovsdb-server.service reload causes the service status to change
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ovsdb-server.sh line 48'
+ message='oe_test_service_ovsdb-server.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ovsdb-server.sh line 48'
Wed Apr 26 14:32:49 2023 - ERROR - oe_test_service_ovsdb-server.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Wed Apr 26 14:32:50 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Apr 26 14:32:51 2023 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Apr 26 14:32:52 2023 - INFO  - start environment cleanup.
+ sed -i 's\ExecStart=/usr/share/openvswitch/scripts/ovs-ctl --no-mlockall\ExecStart=/usr/share/openvswitch/scripts/ovs-ctl\g' /usr/lib/systemd/system/ovsdb-server.service
+ systemctl daemon-reload
+ service ovsdb-server.service reload
oe_test_service_ovsdb-server.sh: line 56: service: command not found
+ service ovsdb-server.service stop
oe_test_service_ovsdb-server.sh: line 57: service: command not found
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpe4utpgo8 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpe4utpgo8
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Wed Apr 26 14:34:06 2023 - INFO  - Finish environment cleanup!
