+ source common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed May  3 21:58:28 2023 - INFO  - Start to prepare the test environment.
+ get_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks='sr0 vdb vdc'
+ disk_list=($disks)
+ disk1=sr0
+ disk2=vdb
+ DNF_INSTALL ntfs-3g
+ pkgs=ntfs-3g
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs ntfs-3g --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp6kluhbmu
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp6kluhbmu
+ mkntfs --fast /dev/sr0
Could not open /dev/sr0: No medium found
+ mkntfs --fast /dev/vdb
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
+ LOG_INFO 'Finish preparing the test environment.'
+ message='Finish preparing the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish preparing the test environment.'
Wed May  3 21:58:46 2023 - INFO  - Finish preparing the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed May  3 21:58:47 2023 - INFO  - Start to run test.
+ ntfsclone --overwrite /dev/sr0 /dev/vdb --new-serial
+ grep Syncing
+ CHECK_RESULT 1 0 0 'Check ntfsclone --new-serial failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsclone --new-serial failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsclone --new-serial failed.'
+ LOG_ERROR 'Check ntfsclone --new-serial failed.'
+ message='Check ntfsclone --new-serial failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check ntfsclone --new-serial failed.'
Wed May  3 21:58:47 2023 - ERROR - Check ntfsclone --new-serial failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsclone_02.sh line 31'
+ message='oe_test_ntfs-3g_ntfsclone_02.sh line 31'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsclone_02.sh line 31'
Wed May  3 21:58:47 2023 - ERROR - oe_test_ntfs-3g_ntfsclone_02.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
+ ntfsclone --overwrite /dev/sr0 /dev/vdb --new-half-serial
+ grep Syncing
+ CHECK_RESULT 1 0 0 'Check ntfsclone --new-half-serial failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsclone --new-half-serial failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsclone --new-half-serial failed.'
+ LOG_ERROR 'Check ntfsclone --new-half-serial failed.'
+ message='Check ntfsclone --new-half-serial failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check ntfsclone --new-half-serial failed.'
Wed May  3 21:58:48 2023 - ERROR - Check ntfsclone --new-half-serial failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsclone_02.sh line 33'
+ message='oe_test_ntfs-3g_ntfsclone_02.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsclone_02.sh line 33'
Wed May  3 21:58:48 2023 - ERROR - oe_test_ntfs-3g_ntfsclone_02.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ ntfsclone --overwrite /dev/sr0 /dev/vdb --preserve-timestamps
+ grep Syncing
+ CHECK_RESULT 1 0 0 'Check ntfsclone --preserve-timestamps failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsclone --preserve-timestamps failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsclone --preserve-timestamps failed.'
+ LOG_ERROR 'Check ntfsclone --preserve-timestamps failed.'
+ message='Check ntfsclone --preserve-timestamps failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check ntfsclone --preserve-timestamps failed.'
Wed May  3 21:58:48 2023 - ERROR - Check ntfsclone --preserve-timestamps failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsclone_02.sh line 35'
+ message='oe_test_ntfs-3g_ntfsclone_02.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsclone_02.sh line 35'
Wed May  3 21:58:49 2023 - ERROR - oe_test_ntfs-3g_ntfsclone_02.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ ntfsclone --overwrite /dev/sr0 /dev/vdb --quiet
+ grep Syncing
+ CHECK_RESULT 1 0 0 'Check ntfsclone --quiet failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsclone --quiet failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsclone --quiet failed.'
+ LOG_ERROR 'Check ntfsclone --quiet failed.'
+ message='Check ntfsclone --quiet failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check ntfsclone --quiet failed.'
Wed May  3 21:58:49 2023 - ERROR - Check ntfsclone --quiet failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsclone_02.sh line 37'
+ message='oe_test_ntfs-3g_ntfsclone_02.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsclone_02.sh line 37'
Wed May  3 21:58:49 2023 - ERROR - oe_test_ntfs-3g_ntfsclone_02.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ ntfsclone --overwrite /dev/sr0 /dev/vdb --force
+ grep Syncing
+ CHECK_RESULT 1 0 0 'Check ntfsclone --force failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsclone --force failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsclone --force failed.'
+ LOG_ERROR 'Check ntfsclone --force failed.'
+ message='Check ntfsclone --force failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check ntfsclone --force failed.'
Wed May  3 21:58:50 2023 - ERROR - Check ntfsclone --force failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsclone_02.sh line 39'
+ message='oe_test_ntfs-3g_ntfsclone_02.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsclone_02.sh line 39'
Wed May  3 21:58:50 2023 - ERROR - oe_test_ntfs-3g_ntfsclone_02.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ ntfsclone --overwrite /dev/sr0 /dev/vdb --full-logfile
+ grep Syncing
+ CHECK_RESULT 1 0 0 'Check ntfsclone --full-logfile failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsclone --full-logfile failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsclone --full-logfile failed.'
+ LOG_ERROR 'Check ntfsclone --full-logfile failed.'
+ message='Check ntfsclone --full-logfile failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check ntfsclone --full-logfile failed.'
Wed May  3 21:58:50 2023 - ERROR - Check ntfsclone --full-logfile failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsclone_02.sh line 41'
+ message='oe_test_ntfs-3g_ntfsclone_02.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsclone_02.sh line 41'
Wed May  3 21:58:51 2023 - ERROR - oe_test_ntfs-3g_ntfsclone_02.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ ntfsfix --help
+ grep 'Usage: ntfsfix \[options\]'
Usage: ntfsfix [options] device
+ CHECK_RESULT 0 0 0 'Check ntfsfix --help failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check ntfsfix --help failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ntfsfix --version
+ grep 'ntfsfix v'
ntfsfix v2022.5.17
+ CHECK_RESULT 0 0 0 'Check ntfsfix --version failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check ntfsfix --version failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ntfsfix --clear-bad-sectors /dev/sr0
+ grep 'NTFS partition /dev/sr0 was processed successfully'
Error opening '/dev/sr0': No medium found
Error opening '/dev/sr0': No medium found
Failed to startup volume: No medium found
Error opening '/dev/sr0': No medium found
Volume is corrupt. You should run chkdsk.
+ CHECK_RESULT 1 0 0 'Check ntfsfix --clear-bad-sectors failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsfix --clear-bad-sectors failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsfix --clear-bad-sectors failed.'
+ LOG_ERROR 'Check ntfsfix --clear-bad-sectors failed.'
+ message='Check ntfsfix --clear-bad-sectors failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check ntfsfix --clear-bad-sectors failed.'
Wed May  3 21:58:51 2023 - ERROR - Check ntfsfix --clear-bad-sectors failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsclone_02.sh line 47'
+ message='oe_test_ntfs-3g_ntfsclone_02.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsclone_02.sh line 47'
Wed May  3 21:58:51 2023 - ERROR - oe_test_ntfs-3g_ntfsclone_02.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ ntfsfix --clear-dirty /dev/sr0
+ grep 'NTFS partition /dev/sr0 was processed successfully'
Error opening '/dev/sr0': No medium found
Error opening '/dev/sr0': No medium found
Failed to startup volume: No medium found
Error opening '/dev/sr0': No medium found
Volume is corrupt. You should run chkdsk.
+ CHECK_RESULT 1 0 0 'Check ntfsfix --clear-dirty failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsfix --clear-dirty failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsfix --clear-dirty failed.'
+ LOG_ERROR 'Check ntfsfix --clear-dirty failed.'
+ message='Check ntfsfix --clear-dirty failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check ntfsfix --clear-dirty failed.'
Wed May  3 21:58:52 2023 - ERROR - Check ntfsfix --clear-dirty failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsclone_02.sh line 49'
+ message='oe_test_ntfs-3g_ntfsclone_02.sh line 49'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsclone_02.sh line 49'
Wed May  3 21:58:52 2023 - ERROR - oe_test_ntfs-3g_ntfsclone_02.sh line 49
+ '[' 0 -eq 1 ']'
+ return 0
+ ntfsfix --no-action /dev/sr0
+ grep 'NTFS partition /dev/sr0 was processed successfully'
Error opening '/dev/sr0': No medium found
Error opening '/dev/sr0': No medium found
Failed to startup volume: No medium found
Error opening '/dev/sr0': No medium found
Volume is corrupt. You should run chkdsk.
+ CHECK_RESULT 1 0 0 'Check ntfsfix --no-action failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsfix --no-action failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsfix --no-action failed.'
+ LOG_ERROR 'Check ntfsfix --no-action failed.'
+ message='Check ntfsfix --no-action failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check ntfsfix --no-action failed.'
Wed May  3 21:58:53 2023 - ERROR - Check ntfsfix --no-action failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsclone_02.sh line 51'
+ message='oe_test_ntfs-3g_ntfsclone_02.sh line 51'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsclone_02.sh line 51'
Wed May  3 21:58:53 2023 - ERROR - oe_test_ntfs-3g_ntfsclone_02.sh line 51
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of the test.'
+ message='End of the test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of the test.'
Wed May  3 21:58:53 2023 - INFO  - End of the test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 9
+ test 9 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed May  3 21:58:54 2023 - ERROR - failed to execute the case.
+ exit 9
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed May  3 21:58:54 2023 - INFO  - Start to restore the test environment.
+ expect
spawn mkfs.ext4 /dev/sr0
y
mke2fs 1.46.5 (30-Dec-2021)
mkfs.ext4: No medium found while trying to determine filesystem size
+ expect
spawn mkfs.ext4 /dev/vdb
y
mke2fs 1.46.5 (30-Dec-2021)
/dev/vdb contains a ntfs file system
Proceed anyway? (y,N) Discarding device blocks:       0/1310720               done                            
Creating filesystem with 1310720 4k blocks and 327680 inodes
Filesystem UUID: 4d573062-39dd-4f33-990b-a0dc5a2f52a3
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736

Allocating group tables:  0/40     done                            
Writing inode tables:  0/40     done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information:  0/40     done

+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp6kluhbmu ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp6kluhbmu
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish restoring the test environment.'
+ message='Finish restoring the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish restoring the test environment.'
Wed May  3 21:58:59 2023 - INFO  - Finish restoring the test environment.
