+ source /root/mugen/libs/locallibs/common_lib.sh
+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ python3 --version
++ '[' 0 -eq 0 ']'
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
+ main
++ type -t post_test
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Tue Jun  6 21:24:39 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL libfabric
+ pkgs=libfabric
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs libfabric --node 1 --tempfile ''
Tue Jun  6 21:24:39 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL libfabric
+ pkgs=libfabric
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs libfabric --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpvikv1ee0
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpvikv1ee0
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
+ tmpfile2='Last metadata expiration check: 0:00:11 ago on Tue 06 Jun 2023 09:24:45 PM UTC.
Dependencies resolved.
================================================================================
 Package             Arch        Version                  Repository       Size
================================================================================
Installing:
 libfabric           x86_64      1.16.1-1.oe2303          everything      683 k
Installing dependencies:
 hwdata              noarch      0.366-1.oe2303           OS              1.7 M
 infinipath-psm      x86_64      3.3-12.oe2303            everything      187 k
 libpsm2             x86_64      10.3.58-9.oe2303         everything      181 k
 numactl-libs        x86_64      2.0.16-3.oe2303          OS               27 k
 pciutils            x86_64      3.9.0-1.oe2303           OS              114 k
 rdma-core           x86_64      41.0-8.oe2303            OS              848 k

Transaction Summary
================================================================================
Install  7 Packages

Total size: 3.7 M
Installed size: 15 M
Downloading Packages:
[SKIPPED] hwdata-0.366-1.oe2303.noarch.rpm: Already downloaded                 
[SKIPPED] numactl-libs-2.0.16-3.oe2303.x86_64.rpm: Already downloaded          
[SKIPPED] pciutils-3.9.0-1.oe2303.x86_64.rpm: Already downloaded               
[SKIPPED] rdma-core-41.0-8.oe2303.x86_64.rpm: Already downloaded               
[SKIPPED] infinipath-psm-3.3-12.oe2303.x86_64.rpm: Already downloaded          
[SKIPPED] libfabric-1.16.1-1.oe2303.x86_64.rpm: Already downloaded             
[SKIPPED] libpsm2-10.3.58-9.oe2303.x86_64.rpm: Already downloaded              
Running transaction check
Waiting for process with pid 3184 to finish.
[Errno 2] No such file or directory: '\''/var/cache/dnf/OS-9d77b3507add28da/packages/hwdata-0.366-1.oe2303.noarch.rpm'\''
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing '\''dnf clean packages'\''.'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 0:00:11 ago on Tue 06 Jun 2023 09:24:45 PM UTC.
Dependencies resolved.
================================================================================
 Package             Arch        Version                  Repository       Size
================================================================================
Installing:
 libfabric           x86_64      1.16.1-1.oe2303          everything      683 k
Installing dependencies:
 hwdata              noarch      0.366-1.oe2303           OS              1.7 M
 infinipath-psm      x86_64      3.3-12.oe2303            everything      187 k
 libpsm2             x86_64      10.3.58-9.oe2303         everything      181 k
 numactl-libs        x86_64      2.0.16-3.oe2303          OS               27 k
 pciutils            x86_64      3.9.0-1.oe2303           OS              114 k
 rdma-core           x86_64      41.0-8.oe2303            OS              848 k

Transaction Summary
================================================================================
Install  7 Packages

Total size: 3.7 M
Installed size: 15 M
Downloading Packages:
[SKIPPED] hwdata-0.366-1.oe2303.noarch.rpm: Already downloaded                 
[SKIPPED] numactl-libs-2.0.16-3.oe2303.x86_64.rpm: Already downloaded          
[SKIPPED] pciutils-3.9.0-1.oe2303.x86_64.rpm: Already downloaded               
[SKIPPED] rdma-core-41.0-8.oe2303.x86_64.rpm: Already downloaded               
[SKIPPED] infinipath-psm-3.3-12.oe2303.x86_64.rpm: Already downloaded          
[SKIPPED] libfabric-1.16.1-1.oe2303.x86_64.rpm: Already downloaded             
[SKIPPED] libpsm2-10.3.58-9.oe2303.x86_64.rpm: Already downloaded              
Running transaction check
Waiting for process with pid 3184 to finish.
[Errno 2] No such file or directory: '\''/var/cache/dnf/OS-9d77b3507add28da/packages/hwdata-0.366-1.oe2303.noarch.rpm'\''
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing '\''dnf clean packages'\''.'
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Tue Jun  6 21:25:05 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Jun  6 21:25:06 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Jun  6 21:25:06 2023 - INFO  - Start to run test.
+ fi_info -h
+ grep 'Usage: fi_info'
Tue Jun  6 21:25:06 2023 - INFO  - Start to run test.
Usage: fi_info
+ CHECK_RESULT 0 0 0 'Check fi_info -h failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fi_info -h failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 'Usage: fi_info'
+ fi_info -h
+ grep 'Usage: fi_info'
+ fi_info --help
Usage: fi_info
+ CHECK_RESULT 0 0 0 'Check fi_info -h failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fi_info -h failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fi_info --help
+ grep 'Usage: fi_info'
Usage: fi_info
+ CHECK_RESULT 0 0 0 'Check fi_info --help failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fi_info --help failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fi_info -n http://127.0.0.1
+ grep 'provider: shm'
Usage: fi_info
+ CHECK_RESULT 0 0 0 'Check fi_info --help failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fi_info --help failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fi_info -n http://127.0.0.1
+ grep 'provider: shm'
provider: shm
provider: shm
+ CHECK_RESULT 0 0 0 'Check fi_info -n failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fi_info -n failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fi_info --node=http://127.0.0.1
+ grep 'provider: shm'
provider: shm
provider: shm
+ CHECK_RESULT 0 0 0 'Check fi_info -n failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fi_info -n failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fi_info --node=http://127.0.0.1
+ grep 'provider: shm'
provider: shm
provider: shm
+ CHECK_RESULT 0 0 0 'Check fi_info --node failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fi_info --node failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fi_info -P 80
+ grep provider:
provider: shm
provider: shm
+ CHECK_RESULT 0 0 0 'Check fi_info --node failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fi_info --node failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fi_info -P 80
+ grep provider:
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: udp;ofi_rxd
provider: shm
provider: shm
provider: udp
provider: tcp
provider: tcp
provider: sockets
provider: sockets
provider: sockets
provider: net
provider: net
provider: net
+ CHECK_RESULT 0 0 0 'Check fi_info -P failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fi_info -P failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fi_info --port=80
+ grep provider:
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: udp;ofi_rxd
provider: shm
provider: shm
provider: udp
provider: tcp
provider: tcp
provider: sockets
provider: sockets
provider: sockets
provider: net
provider: net
provider: net
+ CHECK_RESULT 0 0 0 'Check fi_info -P failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fi_info -P failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep provider:
+ fi_info --port=80
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: udp;ofi_rxd
provider: shm
provider: shm
provider: udp
provider: tcp
provider: tcp
provider: sockets
provider: sockets
provider: sockets
provider: net
provider: net
provider: net
+ CHECK_RESULT 0 0 0 'Check fi_info --port failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fi_info --port failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fi_info -cFI_MSG
+ grep 'provider: UDP'
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: tcp;ofi_rxm
provider: udp;ofi_rxd
provider: shm
provider: shm
provider: udp
provider: tcp
provider: tcp
provider: sockets
provider: sockets
provider: sockets
provider: net
provider: net
provider: net
+ CHECK_RESULT 0 0 0 'Check fi_info --port failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fi_info --port failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fi_info -cFI_MSG
+ grep 'provider: UDP'
+ CHECK_RESULT 1 0 0 'Check fi_info -c failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fi_info -c failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fi_info -c failed'
+ LOG_ERROR 'Check fi_info -c failed'
+ message='Check fi_info -c failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fi_info -c failed'
+ CHECK_RESULT 1 0 0 'Check fi_info -c failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fi_info -c failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fi_info -c failed'
+ LOG_ERROR 'Check fi_info -c failed'
+ message='Check fi_info -c failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fi_info -c failed'
Tue Jun  6 21:25:12 2023 - ERROR - Check fi_info -c failed
Tue Jun  6 21:25:12 2023 - ERROR - Check fi_info -c failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libfabric_fi_info_01.sh line 42'
+ message='oe_test_libfabric_fi_info_01.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_libfabric_fi_info_01.sh line 42'
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libfabric_fi_info_01.sh line 42'
+ message='oe_test_libfabric_fi_info_01.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_libfabric_fi_info_01.sh line 42'
Tue Jun  6 21:25:12 2023 - ERROR - oe_test_libfabric_fi_info_01.sh line 42
Tue Jun  6 21:25:12 2023 - ERROR - oe_test_libfabric_fi_info_01.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'provider: UDP'
+ fi_info --caps=FI_MSG
+ '[' 0 -eq 1 ']'
+ return 0
+ fi_info --caps=FI_MSG
+ grep 'provider: UDP'
+ CHECK_RESULT 1 0 0 'Check fi_info --caps failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fi_info --caps failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fi_info --caps failed'
+ LOG_ERROR 'Check fi_info --caps failed'
+ message='Check fi_info --caps failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fi_info --caps failed'
+ CHECK_RESULT 1 0 0 'Check fi_info --caps failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fi_info --caps failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fi_info --caps failed'
+ LOG_ERROR 'Check fi_info --caps failed'
+ message='Check fi_info --caps failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fi_info --caps failed'
Tue Jun  6 21:25:14 2023 - ERROR - Check fi_info --caps failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libfabric_fi_info_01.sh line 44'
+ message='oe_test_libfabric_fi_info_01.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_libfabric_fi_info_01.sh line 44'
Tue Jun  6 21:25:14 2023 - ERROR - Check fi_info --caps failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libfabric_fi_info_01.sh line 44'
+ message='oe_test_libfabric_fi_info_01.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_libfabric_fi_info_01.sh line 44'
Tue Jun  6 21:25:14 2023 - ERROR - oe_test_libfabric_fi_info_01.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'provider: UDP'
+ fi_info --mode=
Tue Jun  6 21:25:14 2023 - ERROR - oe_test_libfabric_fi_info_01.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ fi_info --mode=
+ grep 'provider: UDP'
+ CHECK_RESULT 1 0 0 'Check fi_info --mode failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fi_info --mode failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fi_info --mode failed'
+ LOG_ERROR 'Check fi_info --mode failed'
+ message='Check fi_info --mode failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fi_info --mode failed'
+ CHECK_RESULT 1 0 0 'Check fi_info --mode failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fi_info --mode failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fi_info --mode failed'
+ LOG_ERROR 'Check fi_info --mode failed'
+ message='Check fi_info --mode failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fi_info --mode failed'
Tue Jun  6 21:25:15 2023 - ERROR - Check fi_info --mode failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libfabric_fi_info_01.sh line 46'
+ message='oe_test_libfabric_fi_info_01.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_libfabric_fi_info_01.sh line 46'
Tue Jun  6 21:25:15 2023 - ERROR - Check fi_info --mode failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libfabric_fi_info_01.sh line 46'
+ message='oe_test_libfabric_fi_info_01.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_libfabric_fi_info_01.sh line 46'
Tue Jun  6 21:25:16 2023 - ERROR - oe_test_libfabric_fi_info_01.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'provider: UDP'
+ fi_info -m ''
Tue Jun  6 21:25:16 2023 - ERROR - oe_test_libfabric_fi_info_01.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'provider: UDP'
+ fi_info -m ''
+ CHECK_RESULT 1 0 0 'Check fi_info -m failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fi_info -m failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fi_info -m failed'
+ LOG_ERROR 'Check fi_info -m failed'
+ message='Check fi_info -m failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fi_info -m failed'
+ CHECK_RESULT 1 0 0 'Check fi_info -m failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fi_info -m failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fi_info -m failed'
+ LOG_ERROR 'Check fi_info -m failed'
+ message='Check fi_info -m failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fi_info -m failed'
Tue Jun  6 21:25:17 2023 - ERROR - Check fi_info -m failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libfabric_fi_info_01.sh line 48'
+ message='oe_test_libfabric_fi_info_01.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_libfabric_fi_info_01.sh line 48'
Tue Jun  6 21:25:17 2023 - ERROR - Check fi_info -m failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libfabric_fi_info_01.sh line 48'
+ message='oe_test_libfabric_fi_info_01.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_libfabric_fi_info_01.sh line 48'
Tue Jun  6 21:25:18 2023 - ERROR - oe_test_libfabric_fi_info_01.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Jun  6 21:25:18 2023 - ERROR - oe_test_libfabric_fi_info_01.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Jun  6 21:25:18 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Jun  6 21:25:18 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Jun  6 21:25:18 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Jun  6 21:25:18 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Jun  6 21:25:19 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 0:00:11 ago on Tue 06 Jun 2023 09:24:45 PM UTC.
Dependencies resolved.
================================================================================
 Package             Arch        Version                  Repository       Size
================================================================================
Installing:
 libfabric           x86_64      1.16.1-1.oe2303          everything      683 k
Installing dependencies:
 hwdata              noarch      0.366-1.oe2303           OS              1.7 M
 infinipath-psm      x86_64      3.3-12.oe2303            everything      187 k
 libpsm2             x86_64      10.3.58-9.oe2303         everything      181 k
 numactl-libs        x86_64      2.0.16-3.oe2303          OS               27 k
 pciutils            x86_64      3.9.0-1.oe2303           OS              114 k
 rdma-core           x86_64      41.0-8.oe2303            OS              848 k

Transaction Summary
================================================================================
Install  7 Packages

Total size: 3.7 M
Installed size: 15 M
Downloading Packages:
[SKIPPED] hwdata-0.366-1.oe2303.noarch.rpm: Already downloaded                 
[SKIPPED] numactl-libs-2.0.16-3.oe2303.x86_64.rpm: Already downloaded          
[SKIPPED] pciutils-3.9.0-1.oe2303.x86_64.rpm: Already downloaded               
[SKIPPED] rdma-core-41.0-8.oe2303.x86_64.rpm: Already downloaded               
[SKIPPED] infinipath-psm-3.3-12.oe2303.x86_64.rpm: Already downloaded          
[SKIPPED] libfabric-1.16.1-1.oe2303.x86_64.rpm: Already downloaded             
[SKIPPED] libpsm2-10.3.58-9.oe2303.x86_64.rpm: Already downloaded              
Running transaction check
Waiting for process with pid 3184 to finish.
[Errno 2] No such file or directory: '/var/cache/dnf/OS-9d77b3507add28da/packages/hwdata-0.366-1.oe2303.noarch.rpm'
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'. ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 0:00:11 ago on Tue 06 Jun 2023 09:24:45 PM UTC.
Dependencies resolved.
================================================================================
 Package             Arch        Version                  Repository       Size
================================================================================
Installing:
 libfabric           x86_64      1.16.1-1.oe2303          everything      683 k
Installing dependencies:
 hwdata              noarch      0.366-1.oe2303           OS              1.7 M
 infinipath-psm      x86_64      3.3-12.oe2303            everything      187 k
 libpsm2             x86_64      10.3.58-9.oe2303         everything      181 k
 numactl-libs        x86_64      2.0.16-3.oe2303          OS               27 k
 pciutils            x86_64      3.9.0-1.oe2303           OS              114 k
 rdma-core           x86_64      41.0-8.oe2303            OS              848 k

Transaction Summary
================================================================================
Install  7 Packages

Total size: 3.7 M
Installed size: 15 M
Downloading Packages:
[SKIPPED] hwdata-0.366-1.oe2303.noarch.rpm: Already downloaded                 
[SKIPPED] numactl-libs-2.0.16-3.oe2303.x86_64.rpm: Already downloaded          
[SKIPPED] pciutils-3.9.0-1.oe2303.x86_64.rpm: Already downloaded               
[SKIPPED] rdma-core-41.0-8.oe2303.x86_64.rpm: Already downloaded               
[SKIPPED] infinipath-psm-3.3-12.oe2303.x86_64.rpm: Already downloaded          
[SKIPPED] libfabric-1.16.1-1.oe2303.x86_64.rpm: Already downloaded             
[SKIPPED] libpsm2-10.3.58-9.oe2303.x86_64.rpm: Already downloaded              
Running transaction check
Waiting for process with pid 3184 to finish.
[Errno 2] No such file or directory: '\''/var/cache/dnf/OS-9d77b3507add28da/packages/hwdata-0.366-1.oe2303.noarch.rpm'\''
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing '\''dnf clean packages'\''.'
Tue Jun  6 21:25:19 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpvikv1ee0 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpvikv1ee0
Traceback (most recent call last):
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
OSError: [Errno 36] File name too long: "Last metadata expiration check: 0:00:11 ago on Tue 06 Jun 2023 09:24:45 PM UTC.\nDependencies resolved.\n================================================================================\n Package             Arch        Version                  Repository       Size\n================================================================================\nInstalling:\n libfabric           x86_64      1.16.1-1.oe2303          everything      683 k\nInstalling dependencies:\n hwdata              noarch      0.366-1.oe2303           OS              1.7 M\n infinipath-psm      x86_64      3.3-12.oe2303            everything      187 k\n libpsm2             x86_64      10.3.58-9.oe2303         everything      181 k\n numactl-libs        x86_64      2.0.16-3.oe2303          OS               27 k\n pciutils            x86_64      3.9.0-1.oe2303           OS              114 k\n rdma-core           x86_64      41.0-8.oe2303            OS              848 k\n\nTransaction Summary\n================================================================================\nInstall  7 Packages\n\nTotal size: 3.7 M\nInstalled size: 15 M\nDownloading Packages:\n[SKIPPED] hwdata-0.366-1.oe2303.noarch.rpm: Already downloaded                 \n[SKIPPED] numactl-libs-2.0.16-3.oe2303.x86_64.rpm: Already downloaded          \n[SKIPPED] pciutils-3.9.0-1.oe2303.x86_64.rpm: Already downloaded               \n[SKIPPED] rdma-core-41.0-8.oe2303.x86_64.rpm: Already downloaded               \n[SKIPPED] infinipath-psm-3.3-12.oe2303.x86_64.rpm: Already downloaded          \n[SKIPPED] libfabric-1.16.1-1.oe2303.x86_64.rpm: Already downloaded             \n[SKIPPED] libpsm2-10.3.58-9.oe2303.x86_64.rpm: Already downloaded              \nRunning transaction check\nWaiting for process with pid 3184 to finish.\n[Errno 2] No such file or directory: '/var/cache/dnf/OS-9d77b3507add28da/packages/hwdata-0.366-1.oe2303.noarch.rpm'\nThe downloaded packages were saved in cache until the next successful transaction.\nYou can remove cached packages by executing 'dnf clean packages'."
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Jun  6 21:25:21 2023 - INFO  - End to restore the test environment.
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Jun  6 21:25:28 2023 - INFO  - End to restore the test environment.
