+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Wed Jun  7 10:38:21 2023 - INFO  - Start environmental preparation.
++ ip route
++ awk '{print $3}'
++ grep 127.0.0.1
+ eth_name=
++ ethtool -T
++ grep 'PTP Hardware Clock'
++ awk '{print $4}'
ethtool: bad command line argument(s)
For more information run ethtool -h
+ '[' '' == none ']'
+ DNF_INSTALL linuxptp
+ pkgs=linuxptp
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs linuxptp --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpvxhalg6v
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpvxhalg6v
+ sed -i 's\-f /etc/ptp4l.conf -i eth0\-f /etc/ptp4l.conf -i \g' /etc/sysconfig/ptp4l
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Wed Jun  7 10:38:38 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Wed Jun  7 10:38:38 2023 - INFO  - Start testing...
+ test_execution ptp4l.service
+ service=ptp4l.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-06-07 10:38:38'
+ test_restart ptp4l.service
+ service=ptp4l.service
+ systemctl restart ptp4l.service
+ CHECK_RESULT 0 0 0 'ptp4l.service restart failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='ptp4l.service restart failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status ptp4l.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'ptp4l.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ptp4l.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ptp4l.service restart failed'
+ LOG_ERROR 'ptp4l.service restart failed'
+ message='ptp4l.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ptp4l.service restart failed'
Wed Jun  7 10:38:44 2023 - ERROR - ptp4l.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Wed Jun  7 10:38:44 2023 - ERROR - ../common/common_lib.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl stop ptp4l.service
+ CHECK_RESULT 0 0 0 'ptp4l.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='ptp4l.service stop failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status ptp4l.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'ptp4l.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ptp4l.service stop failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ptp4l.service stop failed'
+ LOG_ERROR 'ptp4l.service stop failed'
+ message='ptp4l.service stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ptp4l.service stop failed'
Wed Jun  7 10:38:50 2023 - ERROR - ptp4l.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Wed Jun  7 10:38:50 2023 - ERROR - ../common/common_lib.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start ptp4l.service
+ CHECK_RESULT 0 0 0 'ptp4l.service start failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='ptp4l.service start failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status ptp4l.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'ptp4l.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ptp4l.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ptp4l.service start failed'
+ LOG_ERROR 'ptp4l.service start failed'
+ message='ptp4l.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ptp4l.service start failed'
Wed Jun  7 10:38:56 2023 - ERROR - ptp4l.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Wed Jun  7 10:38:57 2023 - ERROR - ../common/common_lib.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ test_enabled ptp4l.service
+ service=ptp4l.service
++ systemctl is-enabled ptp4l.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable ptp4l.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/ptp4l.service
+ find /etc/systemd/system/multi-user.target.wants/ptp4l.service
/etc/systemd/system/multi-user.target.wants/ptp4l.service
+ CHECK_RESULT 0 0 0 'ptp4l.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='ptp4l.service enable failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable ptp4l.service
Removed /etc/systemd/system/multi-user.target.wants/ptp4l.service.
+ find /etc/systemd/system/multi-user.target.wants/ptp4l.service
find: ‘/etc/systemd/system/multi-user.target.wants/ptp4l.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'ptp4l.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='ptp4l.service disable failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2023-06-07 10:38:38' -u ptp4l.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
Jun 07 10:38:38 localhost.localdomain systemd[1]: ptp4l.service: Failed with result 'exit-code'.
Jun 07 10:38:51 localhost.localdomain systemd[1]: ptp4l.service: Failed with result 'exit-code'.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of ptp4l.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of ptp4l.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of ptp4l.service'
+ LOG_ERROR 'There is an error message for the log of ptp4l.service'
+ message='There is an error message for the log of ptp4l.service'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of ptp4l.service'
Wed Jun  7 10:38:59 2023 - ERROR - There is an error message for the log of ptp4l.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Wed Jun  7 10:38:59 2023 - ERROR - ../common/common_lib.sh line 28
+ '[' 0 -eq 1 ']'
+ return 0
+ test_reload ptp4l.service
+ service=ptp4l.service
+ systemctl start ptp4l.service
+ systemctl reload ptp4l.service
+ grep 'Job type reload is not applicable'
Failed to reload ptp4l.service: Job type reload is not applicable for unit ptp4l.service.
+ CHECK_RESULT 0 0 0 'Job type reload is not applicable for unit ptp4l.service'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit ptp4l.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl status ptp4l.service
+ grep 'Active: active'
+ systemctl status ptp4l.service
+ grep 'inactive (dead)'
+ return 1
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Wed Jun  7 10:39:00 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Jun  7 10:39:00 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Jun  7 10:39:01 2023 - INFO  - start environment cleanup.
+ sed -i 's\-f /etc/ptp4l.conf -i \-f /etc/ptp4l.conf -i eth0\g' /etc/sysconfig/ptp4l
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpvxhalg6v ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpvxhalg6v
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Wed Jun  7 10:39:07 2023 - INFO  - Finish environment cleanup!
