Ã— target.service - Restore LIO kernel target configuration
     Loaded: loaded (/usr/lib/systemd/system/target.service; bad; vendor preset: disabled)
     Active: failed (Result: exit-code) since Sat 2023-04-29 05:47:43 CST; 41s ago
   Main PID: 20453 (code=exited, status=1/FAILURE)

Apr 29 05:47:43 openeuler-riscv64 target[20453]:   File "/usr/bin/targetctl", line 47, in restore
Apr 29 05:47:43 openeuler-riscv64 target[20453]:     errors = RTSRoot().restore_from_file(restore_file=from_file)
Apr 29 05:47:43 openeuler-riscv64 target[20453]:   File "/usr/lib/python3.10/site-packages/rtslib_fb/root.py", line 79, in __init__
Apr 29 05:47:43 openeuler-riscv64 target[20453]:     modprobe('configfs')
Apr 29 05:47:43 openeuler-riscv64 target[20453]:   File "/usr/lib/python3.10/site-packages/rtslib_fb/utils.py", line 438, in modprobe
Apr 29 05:47:43 openeuler-riscv64 target[20453]:     raise RTSLibError("Could not load module: %s" % module)
Apr 29 05:47:43 openeuler-riscv64 target[20453]: rtslib_fb.utils.RTSLibError: Could not load module: configfs
Apr 29 05:47:43 openeuler-riscv64 systemd[1]: target.service: Main process exited, code=exited, status=1/FAILURE
Apr 29 05:47:43 openeuler-riscv64 systemd[1]: target.service: Failed with result 'exit-code'.
Apr 29 05:47:43 openeuler-riscv64 systemd[1]: Failed to start Restore LIO kernel target configuration.
