+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Wed May  3 01:56:10 2023 - INFO  - Start to prepare the database config.
+ DNF_INSTALL 'dump xfsdump'
+ pkgs='dump xfsdump'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'dump xfsdump' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmprm6egxxf
+ '[' -z '' ']'
+ tmpfile=/tmp/tmprm6egxxf
+ point_list=($(CREATE_FS))
++ CREATE_FS
++ fs_type='ext3 ext4 xfs'
+++ date +%Y%m%d%H%M%S
++ cur_date=20230503015634
+++ CREATE_VG
++++ date +%Y%m%d%H%M%S
+++ cur_date=20230503015634
++++ lsblk
++++ grep disk
++++ awk '{print $1}'
++++ tail -n 1
+++ free_disk=vdb
+++ disk_name=/dev/vdb
+++ pvcreate /dev/vdb -f
+++ [[ 127 -eq 0 ]]
++++ pvcreate /dev/vdb
++++ grep test_vggroup
++++ cut -d '"' -f 4
+++ vggroup=
+++ printf
printf: usage: printf [-v var] format [arguments]
++ vggroup=
++ count=1
++ msg=' '
++ for fs in ${fs_type[@]}
++ lvname=test_lv120230503015634
++ point=/tmp/point120230503015634
++ lvcreate -n test_lv120230503015634 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext3 /dev//test_lv120230503015634
mke2fs 1.46.5 (30-Dec-2021)
The file /dev//test_lv120230503015634 does not exist and no size was specified.
++ mkdir /tmp/point120230503015634
++ mount /dev//test_lv120230503015634 /tmp/point120230503015634
mount: /tmp/point120230503015634: special device /dev//test_lv120230503015634 does not exist.
++ msg=' /tmp/point120230503015634 '
++ count=2
++ for fs in ${fs_type[@]}
++ lvname=test_lv220230503015634
++ point=/tmp/point220230503015634
++ lvcreate -n test_lv220230503015634 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext4 /dev//test_lv220230503015634
mke2fs 1.46.5 (30-Dec-2021)
The file /dev//test_lv220230503015634 does not exist and no size was specified.
++ mkdir /tmp/point220230503015634
++ mount /dev//test_lv220230503015634 /tmp/point220230503015634
mount: /tmp/point220230503015634: special device /dev//test_lv220230503015634 does not exist.
++ msg=' /tmp/point120230503015634 /tmp/point220230503015634 '
++ count=3
++ for fs in ${fs_type[@]}
++ lvname=test_lv320230503015634
++ point=/tmp/point320230503015634
++ lvcreate -n test_lv320230503015634 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t xfs /dev//test_lv320230503015634
Error accessing specified device /dev//test_lv320230503015634: No such file or directory
Usage: mkfs.xfs
/* blocksize */		[-b size=num]
/* config file */	[-c options=xxx]
/* metadata */		[-m crc=0|1,finobt=0|1,uuid=xxx,rmapbt=0|1,reflink=0|1,
			    inobtcount=0|1,bigtime=0|1]
/* data subvol */	[-d agcount=n,agsize=n,file,name=xxx,size=num,
			    (sunit=value,swidth=value|su=num,sw=num|noalign),
			    sectsize=num
/* force overwrite */	[-f]
/* inode size */	[-i perblock=n|size=num,maxpct=n,attr=0|1|2,
			    projid32bit=0|1,sparse=0|1,nrext64=0|1]
/* no discard */	[-K]
/* log subvol */	[-l agnum=n,internal,size=num,logdev=xxx,version=n
			    sunit=value|su=num,sectsize=num,lazy-count=0|1]
/* label */		[-L label (maximum 12 characters)]
/* naming */		[-n size=num,version=2|ci,ftype=0|1]
/* no-op info only */	[-N]
/* prototype file */	[-p fname]
/* quiet */		[-q]
/* realtime subvol */	[-r extsize=num,size=num,rtdev=xxx]
/* sectorsize */	[-s size=num]
/* version */		[-V]
			devicename
<devicename> is required unless -d name=xxx is given.
<num> is xxx (bytes), xxxs (sectors), xxxb (fs blocks), xxxk (xxx KiB),
      xxxm (xxx MiB), xxxg (xxx GiB), xxxt (xxx TiB) or xxxp (xxx PiB).
<value> is xxx (512 byte blocks).
++ mkdir /tmp/point320230503015634
++ mount /dev//test_lv320230503015634 /tmp/point320230503015634
mount: /tmp/point320230503015634: special device /dev//test_lv320230503015634 does not exist.
++ msg=' /tmp/point120230503015634 /tmp/point220230503015634 /tmp/point320230503015634 '
++ count=4
++ echo /tmp/point120230503015634 /tmp/point220230503015634 /tmp/point320230503015634
++ vgdisplay
++ grep 'VG Name'
oe_test_snapshot_dump.sh: line 25: vgdisplay: command not found
++ tail -n 1
++ awk '{print $3}'
+ group_name=
++ seq 1 2
+ for i in $(seq 1 $((${#point_list[@]} - 1)))
+ var=/tmp/point220230503015634
+ echo 'test write file'
+ mkdir /tmp/point220230503015634/test_dir
+ for i in $(seq 1 $((${#point_list[@]} - 1)))
+ var=/tmp/point320230503015634
+ echo 'test write file'
+ mkdir /tmp/point320230503015634/test_dir
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Wed May  3 01:56:35 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed May  3 01:56:35 2023 - INFO  - Start to run test.
++ seq 1 2
+ for i in $(seq 1 $((${#point_list[@]} - 1)))
+ var=/tmp/point220230503015634
++ df -iT
++ grep /tmp/point220230503015634
++ awk '{print $1}'
+ lv_name=
++ df -iT
++ grep /tmp/point220230503015634
++ awk '{print $2}'
+ fs_type=
+ [[ '' == \x\f\s ]]
+ dump -0f /tmp/test_dump.dump /tmp/point220230503015634
  DUMP: Date of this level 0 dump: Wed May  3 01:56:36 2023
  DUMP: Dumping /dev/vda2 (/ (dir tmp/point220230503015634)) to /tmp/test_dump.dump
  DUMP: Label: rootfs
  DUMP: Writing 10 Kilobyte records
  DUMP: mapping (Pass I) [regular files]
/dev/vda2: File not found by ext2_lookup while translating tmp/point220230503015634
+ rm -rf /tmp/point220230503015634/test_dir /tmp/point220230503015634/test_file
+ cd /tmp/point220230503015634
+ restore -rf /tmp/test_dump.dump
restore: /tmp/test_dump.dump: No such file or directory
+ CHECK_RESULT 1 0 0 'Dump data failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Dump data failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Dump data failed.'
+ LOG_ERROR 'Dump data failed.'
+ message='Dump data failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Dump data failed.'
Wed May  3 01:56:36 2023 - ERROR - Dump data failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_snapshot_dump.sh line 52'
+ message='oe_test_snapshot_dump.sh line 52'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_snapshot_dump.sh line 52'
Wed May  3 01:56:36 2023 - ERROR - oe_test_snapshot_dump.sh line 52
+ '[' 0 -eq 1 ']'
+ return 0
+ cd -
/root/mugen/testcases/system-test/fs-test/FS_Device
+ test -f /tmp/point220230503015634/restoresymtable
+ CHECK_RESULT 1 0 0 'The file restoresymtable doesn'\''t exist.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The file restoresymtable doesn'\''t exist.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The file restoresymtable doesn'\''t exist.'
+ LOG_ERROR 'The file restoresymtable doesn'\''t exist.'
+ message='The file restoresymtable doesn'\''t exist.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The file restoresymtable doesn'\''t exist.'
Wed May  3 01:56:36 2023 - ERROR - The file restoresymtable doesn't exist.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_snapshot_dump.sh line 55'
+ message='oe_test_snapshot_dump.sh line 55'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_snapshot_dump.sh line 55'
Wed May  3 01:56:37 2023 - ERROR - oe_test_snapshot_dump.sh line 55
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -q test /tmp/point220230503015634/test_file
grep: /tmp/point220230503015634/test_file: No such file or directory
+ CHECK_RESULT 2 0 0 'Check data failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check data failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check data failed.'
+ LOG_ERROR 'Check data failed.'
+ message='Check data failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check data failed.'
Wed May  3 01:56:37 2023 - ERROR - Check data failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_snapshot_dump.sh line 58'
+ message='oe_test_snapshot_dump.sh line 58'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_snapshot_dump.sh line 58'
Wed May  3 01:56:37 2023 - ERROR - oe_test_snapshot_dump.sh line 58
+ '[' 0 -eq 1 ']'
+ return 0
+ rm -rf /tmp/test_dump.dump
+ for i in $(seq 1 $((${#point_list[@]} - 1)))
+ var=/tmp/point320230503015634
++ df -iT
++ grep /tmp/point320230503015634
++ awk '{print $1}'
+ lv_name=
++ df -iT
++ grep /tmp/point320230503015634
++ awk '{print $2}'
+ fs_type=
+ [[ '' == \x\f\s ]]
+ dump -0f /tmp/test_dump.dump /tmp/point320230503015634
  DUMP: Date of this level 0 dump: Wed May  3 01:56:37 2023
  DUMP: Dumping /dev/vda2 (/ (dir tmp/point320230503015634)) to /tmp/test_dump.dump
  DUMP: Label: rootfs
  DUMP: Writing 10 Kilobyte records
  DUMP: mapping (Pass I) [regular files]
/dev/vda2: File not found by ext2_lookup while translating tmp/point320230503015634
+ rm -rf /tmp/point320230503015634/test_dir /tmp/point320230503015634/test_file
+ cd /tmp/point320230503015634
+ restore -rf /tmp/test_dump.dump
restore: /tmp/test_dump.dump: No such file or directory
+ CHECK_RESULT 1 0 0 'Dump data failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Dump data failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Dump data failed.'
+ LOG_ERROR 'Dump data failed.'
+ message='Dump data failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Dump data failed.'
Wed May  3 01:56:38 2023 - ERROR - Dump data failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_snapshot_dump.sh line 52'
+ message='oe_test_snapshot_dump.sh line 52'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_snapshot_dump.sh line 52'
Wed May  3 01:56:38 2023 - ERROR - oe_test_snapshot_dump.sh line 52
+ '[' 0 -eq 1 ']'
+ return 0
+ cd -
/root/mugen/testcases/system-test/fs-test/FS_Device
+ test -f /tmp/point320230503015634/restoresymtable
+ CHECK_RESULT 1 0 0 'The file restoresymtable doesn'\''t exist.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The file restoresymtable doesn'\''t exist.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The file restoresymtable doesn'\''t exist.'
+ LOG_ERROR 'The file restoresymtable doesn'\''t exist.'
+ message='The file restoresymtable doesn'\''t exist.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The file restoresymtable doesn'\''t exist.'
Wed May  3 01:56:38 2023 - ERROR - The file restoresymtable doesn't exist.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_snapshot_dump.sh line 55'
+ message='oe_test_snapshot_dump.sh line 55'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_snapshot_dump.sh line 55'
Wed May  3 01:56:39 2023 - ERROR - oe_test_snapshot_dump.sh line 55
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -q test /tmp/point320230503015634/test_file
grep: /tmp/point320230503015634/test_file: No such file or directory
+ CHECK_RESULT 2 0 0 'Check data failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check data failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check data failed.'
+ LOG_ERROR 'Check data failed.'
+ message='Check data failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check data failed.'
Wed May  3 01:56:39 2023 - ERROR - Check data failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_snapshot_dump.sh line 58'
+ message='oe_test_snapshot_dump.sh line 58'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_snapshot_dump.sh line 58'
Wed May  3 01:56:39 2023 - ERROR - oe_test_snapshot_dump.sh line 58
+ '[' 0 -eq 1 ']'
+ return 0
+ rm -rf /tmp/test_dump.dump
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed May  3 01:56:39 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed May  3 01:56:40 2023 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed May  3 01:56:40 2023 - INFO  - Start to restore the test environment.
++ echo /tmp/point120230503015634 /tmp/point220230503015634 /tmp/point320230503015634
+ list='/tmp/point120230503015634 /tmp/point220230503015634 /tmp/point320230503015634'
+ REMOVE_FS '/tmp/point120230503015634 /tmp/point220230503015634 /tmp/point320230503015634'
+ point_list=($1)
++ seq 0 2
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point120230503015634
++ df -T
++ grep /tmp/point120230503015634
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point220230503015634
++ df -T
++ grep /tmp/point220230503015634
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point320230503015634
++ df -T
++ grep /tmp/point320230503015634
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmprm6egxxf ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmprm6egxxf
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed May  3 01:56:46 2023 - INFO  - End to restore the test environment.
